"""Added account table

Revision ID: 3d59f5ec282e
Revises: 50714ca6c847
Create Date: 2021-03-17 10:54:30.734512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d59f5ec282e'
down_revision = '50714ca6c847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.drop_column('account', 'description')
    op.drop_column('account', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('account', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('account', 'first_name')
    # ### end Alembic commands ###
