version: '2'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=database